C:\Python26>python.exe tracert.py 193.145.222.100
WARNING: No route found for IPv6 destination :: (no default route?)
1       296 ms  140 ms  141 ms  181.166.144.1
2       *       *       *       Request timed out.
3       *       *       *       Request timed out.
4       *       *       *       Request timed out.
5       139 ms  141 ms  140 ms  200.89.165.173
6       140 ms  140 ms  140 ms  200.89.165.130
7       140 ms  140 ms  141 ms  200.89.165.222
8       139 ms  140 ms  141 ms  200.63.151.57
9       139 ms  141 ms  140 ms  200.51.208.62
10      139 ms  141 ms  *       84.16.9.233
11      249 ms  250 ms  249 ms  94.142.123.26
12      250 ms  250 ms  248 ms  94.142.126.177
13      250 ms  249 ms  250 ms  213.140.52.34
14      250 ms  249 ms  250 ms  154.54.7.157
15      248 ms  250 ms  250 ms  154.54.42.26
16      358 ms  358 ms  359 ms  154.54.46.102
17      373 ms  358 ms  359 ms  130.117.2.250
18      358 ms  358 ms  358 ms  130.117.3.118
19      358 ms  358 ms  358 ms  149.11.68.50
20      358 ms  358 ms  467 ms  130.206.245.2
21      358 ms  359 ms  358 ms  130.206.214.142
22      *       *       *       Request timed out.
23      358 ms  358 ms  358 ms  193.145.222.100

Trace complete.